import type { NextPage } from "next";
import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import ListCompany from "./list-company";
import LoginToDoashbord from "./LoginToDoashbord";
import LoginPage from "./loginPage";
import PhoneVerification from "./phoneVerification";

const Home: NextPage = () => {
  const [enteredLogin, setEnteredLogin] = useState<boolean>();
  const [enteredLoginTrue, setEnteredLoginTrue] = useState<boolean>(true);
  const [enteredPhoneVerificatoin, setPhoneVerificatoine] = useState(true);

  const handleLoginPage = () => {
    setEnteredLoginTrue(false);
  };

  /* const handleListCompany = () => {
    setEnteredLogin(true);
  };


  const handleNextLoginPage = () => {
    setPhoneVerificatoine(false);
  };
 */
  //const handleLogOut = () => {
  //setPhoneVerificatoine(false);
  // };

  return (
    <React.Fragment>
      {enteredLogin && <ListCompany handleLoginPage={handleLoginPage} />}
      {/*   <Head>
        <title>Rekar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {enteredLoginTrue && (
          <LoginPage
            handleListCompany={handleListCompany}
            handleLoginPage={handleLoginPage}
          />
        )}
        {!enteredLoginTrue && (
          <LoginToDoashbord handleNextLoginPage={handleNextLoginPage} />
        )}
        {!enteredPhoneVerificatoin && <PhoneVerification />}
      </div> */}
    </React.Fragment>
  );
};

export default Home;
